// <auto-generated />
using System;
using MassTransitUi.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MassTransitUi.Server.Migrations
{
    [DbContext(typeof(MassTransitUiContext))]
    partial class MassTransitUiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("MassTransitUi.Shared.FailedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecievedTsUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FailedMessages");
                });

            modelBuilder.Entity("MassTransitUi.Shared.FailedMessageHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FailedMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FailedMessageId");

                    b.ToTable("FailedMessageHeader");
                });

            modelBuilder.Entity("MassTransitUi.Shared.FailedMessageHeader", b =>
                {
                    b.HasOne("MassTransitUi.Shared.FailedMessage", null)
                        .WithMany("Headers")
                        .HasForeignKey("FailedMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransitUi.Shared.FailedMessage", b =>
                {
                    b.Navigation("Headers");
                });
#pragma warning restore 612, 618
        }
    }
}
